
logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost/mybatis_plus?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password:

mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*Mapper.xml